#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Nov 27 00:31:35 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ticket(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ticket.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 514))
        self.SetTitle("frame_4")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./ticket.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Ticket")
        label_1.SetForegroundColour(wx.Colour(142, 35, 35))
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 35)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./ticket.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_2, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_2.SetForegroundColour(wx.Colour(219, 112, 147))
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbTaquilla.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotalTaquilla.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_3.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        label_5.SetForegroundColour(wx.Colour(219, 112, 147))
        label_5.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_3.Add(label_5, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        lbDulceria.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_4.Add(lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotalDulceria.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_4.Add(lbSubtotalDulceria, 0, wx.ALL, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Total: $")
        lbTotal.SetForegroundColour(wx.Colour(146, 0, 0))
        lbTotal.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(lbTotal, 0, wx.ALIGN_RIGHT | wx.ALL, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetForegroundColour(wx.Colour(204, 50, 50))
        self.btnCancelar.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_5.Add(self.btnCancelar, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetForegroundColour(wx.Colour(66, 111, 66))
        self.btnFinalizar.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_5.Add(self.btnFinalizar, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ticket.<event_handler>
        print("Event handler 'cancelarVenta' not implemented!")
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ticket.<event_handler>
        print("Event handler 'finalizarVenta' not implemented!")
        event.Skip()

# end of class Ticket

class PersonalizaCombo(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PersonalizaCombo.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("PersonalizaCombo")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class PersonalizaCombo

class Dulceria(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dulceria.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((868, 865))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulcerial.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_1, 0, 0, 0)

        tfDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria", style=wx.ALIGN_CENTER_HORIZONTAL)
        tfDulceria.SetForegroundColour(wx.Colour(219, 112, 147))
        tfDulceria.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_2.Add(tfDulceria, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulcerial.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_2, 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_6.Add(self.spComboB, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.button_1 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "OK")
        sizer_6.Add(self.button_1, 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Individual $80")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_4.Add(label_1, 0, wx.ALL, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas CH")
        label_2.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_5.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco CH")
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_5.Add(label_3, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./individual.png", wx.BITMAP_TYPE_ANY))
        sizer_3.Add(bitmap_3, 0, 0, 0)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_7.Add(self.spComboF, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        self.button_1 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "OK")
        sizer_7.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_9, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_9.Add(label_4, 0, wx.ALL, 0)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 Palomitas G")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_10.Add(label_5, 0, wx.ALL, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 Refrescos G")
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_10.Add(label_6, 0, 0, 0)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_8, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./individual.png", wx.BITMAP_TYPE_ANY))
        sizer_8.Add(bitmap_4, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./individual.png", wx.BITMAP_TYPE_ANY))
        sizer_8.Add(bitmap_5, 0, 0, 0)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_11, 1, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_12.Add(self.spComboC, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "OK")
        sizer_12.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_11.Add(sizer_16, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Jumbo $280")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_16.Add(label_7, 0, 0, 0)

        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_16.Add(sizer_17, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G")
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_17.Add(label_8, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 Refrescos G")
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_17.Add(label_9, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Hot Dog")
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_17.Add(label_10, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Nachos ")
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_17.Add(label_11, 0, 0, 0)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(sizer_13, 1, wx.EXPAND, 0)

        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./hotdogy.png", wx.BITMAP_TYPE_ANY))
        sizer_14.Add(bitmap_6, 0, 0, 0)

        bitmap_8 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refrescos.png", wx.BITMAP_TYPE_ANY))
        sizer_14.Add(bitmap_8, 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_13.Add(sizer_15, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./nachos.png", wx.BITMAP_TYPE_ANY))
        sizer_15.Add(bitmap_7, 0, 0, 0)

        bitmap_9 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refrescos.png", wx.BITMAP_TYPE_ANY))
        sizer_15.Add(bitmap_9, 0, 0, 0)

        bitmap_10 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomita.png", wx.BITMAP_TYPE_ANY))
        sizer_13.Add(bitmap_10, 0, 0, 0)

        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_20, 1, wx.EXPAND, 0)

        bitmap_11 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomita.png", wx.BITMAP_TYPE_ANY))
        sizer_20.Add(bitmap_11, 0, 0, 0)

        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        sizer_20.Add(sizer_21, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_16.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_21.Add(label_16, 0, 0, 0)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21.Add(sizer_22, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_22.Add(self.spPalomitasCh, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "CH")
        label_17.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_22.Add(label_17, 0, 0, 0)

        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21.Add(sizer_23, 1, wx.EXPAND, 0)

        self.spPalomitasMed = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_23.Add(self.spPalomitasMed, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "MED")
        label_18.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_23.Add(label_18, 0, 0, 0)

        sizer_24 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21.Add(sizer_24, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_24.Add(self.spPalomitasG, 0, 0, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "GRD")
        label_19.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_24.Add(label_19, 0, 0, 0)

        bitmap_12 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refresco1.png", wx.BITMAP_TYPE_ANY))
        sizer_20.Add(bitmap_12, 0, 0, 0)

        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_20.Add(sizer_25, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_20.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_25.Add(label_20, 0, 0, 0)

        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_25.Add(sizer_26, 1, wx.EXPAND, 0)

        sizer_27 = wx.BoxSizer(wx.VERTICAL)
        sizer_26.Add(sizer_27, 1, wx.EXPAND, 0)

        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27.Add(sizer_28, 1, wx.EXPAND, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_21.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_28.Add(label_21, 0, wx.ALL, 15)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_22.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_28.Add(label_22, 0, wx.ALL, 15)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_23.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        sizer_28.Add(label_23, 0, wx.ALL, 15)

        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27.Add(sizer_29, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_29.Add(self.cmbTamano, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_29.Add(self.cmbSabor, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_29.Add(self.spCantidad, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        sizer_29.Add(self.btnAgregar, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_18, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:")
        label_12.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Britannic Bold"))
        sizer_18.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "--")
        lbProductosAgregados.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_18.Add(lbProductosAgregados, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Combos:")
        label_14.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Britannic Bold"))
        sizer_18.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        lbSubtotal.SetForegroundColour(wx.Colour(255, 0, 0))
        lbSubtotal.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Britannic Bold"))
        sizer_18.Add(lbSubtotal, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_19, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetFont(wx.Font(20, wx.FONTFAMILY_SCRIPT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Papyrus"))
        sizer_19.Add(self.btnLimpiar, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(22, wx.FONTFAMILY_SCRIPT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Papyrus"))
        sizer_19.Add(self.btnSiguiente, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMed.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMed)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularComboBasico' not implemented!")
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularComboFamiliar' not implemented!")
        event.Skip()

    def calcularComboCuates(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularComboCuates' not implemented!")
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularPalomitasCh' not implemented!")
        event.Skip()

    def calcularPalomitasMed(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularPalomitasMed' not implemented!")
        event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'calcularPalomitasG' not implemented!")
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'agregarRefresco' not implemented!")
        event.Skip()

    def limpiarDulceria(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'limpiarDulceria' not implemented!")
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: Dulceria.<event_handler>
        print("Event handler 'siguienteDulceria' not implemented!")
        event.Skip()

# end of class Dulceria

class Taquilla(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Taquilla.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((630, 690))
        self.SetTitle("Taquilla")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(95, 159, 159))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipopeliculas.jfif", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_1, 0, wx.ALL, 4)

        tfTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla", style=wx.ALIGN_CENTER_HORIZONTAL)
        tfTaquilla.SetMinSize((125, 35))
        tfTaquilla.SetForegroundColour(wx.Colour(0, 0, 255))
        tfTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Broadway"))
        sizer_2.Add(tfTaquilla, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipopeliculas.jfif", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_2, 0, wx.ALL, 4)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_6.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 18)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_6.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 19)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_6.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 18)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Annabelle", "Rio", "El telefono negro"], style=wx.CB_DROPDOWN)
        sizer_7.Add(self.cmbPelicula, 0, wx.ALL, 18)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "--")
        lbSala.SetForegroundColour(wx.Colour(255, 255, 255))
        lbSala.SetFont(wx.Font(22, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_7.Add(lbSala, 0, 0, 0)

        grid_sizer_1 = wx.GridSizer(3, 1, 0, 0)
        sizer_7.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.rbHorario = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_1.Add(self.rbHorario, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 1)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_1.Add(self.rbHorario2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00.00")
        self.rbHorario3.SetForegroundColour(wx.Colour(255, 255, 255))
        grid_sizer_1.Add(self.rbHorario3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./peli1.png", wx.BITMAP_TYPE_ANY))
        sizer_4.Add(bmPelicula, 0, wx.ALL, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(22, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Bernard MT Condensed"))
        sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 11)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($50):")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_8.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 14)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_9.Add(self.tfAdultos, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Niños ($35):")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_9.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 14)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_9.Add(self.tfMenores, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotal.SetForegroundColour(wx.Colour(255, 255, 255))
        lbSubtotal.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_1.Add(lbSubtotal, 0, wx.ALL, 6)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_10, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((124, 50))
        self.btnLimpiar.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_10.Add(self.btnLimpiar, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((146, 50))
        self.btnSiguiente.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Stencil"))
        sizer_10.Add(self.btnSiguiente, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 8)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.SeleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def seleccionPelicula(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'seleccionPelicula' not implemented!")
        event.Skip()

    def seleccionHorario(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'seleccionHorario' not implemented!")
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'seleccionHorario2' not implemented!")
        event.Skip()

    def SeleccionHorario3(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'SeleccionHorario3' not implemented!")
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'sumarAdultos' not implemented!")
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'sumarMenores' not implemented!")
        event.Skip()

    def limpiarTaquilla(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'limpiarTaquilla' not implemented!")
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Taquilla.<event_handler>
        print("Event handler 'siguienteVentana' not implemented!")
        event.Skip()

# end of class Taquilla

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 444))
        self.SetTitle(u"Inicio de sesión-Cine Plus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("E:\\CinePlusElizabeth3A\\logotipo.jfif", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(216, 216, 191))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        IbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbTitulo.SetMinSize((132, 35))
        IbTitulo.SetForegroundColour(wx.Colour(95, 159, 159))
        IbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbTitulo, 0, wx.EXPAND, 0)

        IbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.jfif", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(IbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario")
        IbUsuario.SetMinSize((123, 20))
        IbUsuario.SetForegroundColour(wx.Colour(95, 159, 159))
        IbUsuario.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña")
        IbClave.SetMinSize((123, 20))
        IbClave.SetForegroundColour(wx.Colour(95, 159, 159))
        IbClave.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial Narrow"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'confirmar_usuario_clave' not implemented!")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class Ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
