#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Oct  7 08:59:01 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 444))
        self.SetTitle(u"Inicio de sesión-Cine Plus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("E:\\CinePlusElizabeth3A\\logotipo.jfif", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(216, 216, 191))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        IbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbTitulo.SetMinSize((132, 35))
        IbTitulo.SetForegroundColour(wx.Colour(95, 159, 159))
        IbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbTitulo, 0, wx.EXPAND, 0)

        IbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.jfif", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(IbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario")
        IbUsuario.SetMinSize((123, 20))
        IbUsuario.SetForegroundColour(wx.Colour(95, 159, 159))
        IbUsuario.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña")
        IbClave.SetMinSize((123, 20))
        IbClave.SetForegroundColour(wx.Colour(95, 159, 159))
        IbClave.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(IbClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial Narrow"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre=self.tfUsuario.GetValue ( )
        clave=self.tfClave.GetValue ( )

        if nombre== "Eli" and clave=="123":
            print(f"¡Bienvenida; {nombre}! Acceso autorizado.")

        else:
            print("Acceso denegado, Usuario o Clave incorrectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta=wx.MessageDialog(self, "se cerrara la ventana.\n "\
        "¿Esta seguro que desea salir?","Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta=pregunta.ShowModal()
        pregunta.Destroy()#cerramos el dialogo

        if respuesta == wx.ID_YES:
            print("¡Bye!")
            self.Close()
        event.Skip()

# end of class Ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
